import { DELETE_CUSTOMER_ACCOUNT } from "./DELETE_CUSTOMER_ACCOUNT.js";
import { CUSTOMER_TECHNICIAN_LIST } from "./CUSTOMER_TECHNICIAN_LIST.js";
import { CREATE_CUSTOMER_ACCOUNT } from "./CREATE_CUSTOMER_ACCOUNT.js";
import { CUSTOMER_ACCOUNT } from "./CUSTOMER_ACCOUNT.js";
import { UPDATE_CUSTOMER } from "./UPDATE_CUSTOMER.js";
import { GET_TECHNICIAN_LIST } from "./GET_TECHNICIAN_LIST.js";
import { GET_TECHNICIAN } from "./GET_TECHNICIAN.js";
import { CREATE_TECHNICIAN } from "./CREATE_TECHNICIAN.js";
import { UPDATE_TECHNICIAN } from "./UPDATE_TECHNICIAN.js";
import { GET_SERVICE_ROUTES } from "./GET_SERVICE_ROUTES.js";
import { GET_ALL_SERVICE_ROUTES } from "./GET_ALL_ROUTES.js";
import { UPDATE_ACCOUNT_TECHNICIAN } from "./UPDATE_ACCOUNT_TECHNICIAN.js";
import { REGISTER_TECHNICIAN } from "./REGISTER_TECHNICIAN.js";
import { GET_REGISTRATION_TECHNICIAN } from "./GET_REGISTRATION_TECHNICIAN.js";
import { GET_SERVICE_ROUTE_BY_TECH_ID } from "./GET_SERVICE_ROUTE_BY_TECH_ID.js";
import { UPDATE_CUSTOMERS } from "./UPDATE_CUSTOMERS.js";
import { DELETE_ACCOUNT_OWNER } from "./DELETE_ACCOUNT_OWNER.js";
import { CREATE_ACCOUNT_OWNERS } from "./CREATE_ACCOUNT_OWNERS.js";
export {
  CREATE_ACCOUNT_OWNERS,
  DELETE_ACCOUNT_OWNER,
  UPDATE_CUSTOMERS,
  GET_SERVICE_ROUTE_BY_TECH_ID,
  GET_REGISTRATION_TECHNICIAN,
  REGISTER_TECHNICIAN,
  UPDATE_ACCOUNT_TECHNICIAN,
  GET_ALL_SERVICE_ROUTES,
  GET_SERVICE_ROUTES,
  UPDATE_TECHNICIAN,
  CREATE_TECHNICIAN,
  DELETE_CUSTOMER_ACCOUNT,
  CUSTOMER_TECHNICIAN_LIST,
  CREATE_CUSTOMER_ACCOUNT,
  CUSTOMER_ACCOUNT,
  UPDATE_CUSTOMER,
  GET_TECHNICIAN_LIST,
  GET_TECHNICIAN,
};
