import { CUSTOMER_LIST } from "./CUSTOMER_LIST.js";
import { DELETE_CUSTOMER_ACCOUNT } from "./DELETE_CUSTOMER_ACCOUNT.js";
import { CUSTOMER_TECHNICIAN_LIST } from "./CUSTOMER_TECHNICIAN_LIST.js";
import { CREATE_NEW_CUSTOMER } from "./CREATE_NEW_CUSTOMER.js";

export {
  CUSTOMER_LIST,
  DELETE_CUSTOMER_ACCOUNT,
  CUSTOMER_TECHNICIAN_LIST,
  CREATE_NEW_CUSTOMER,
};
