import { CUSTOMER_LIST } from "./CUSTOMER_LIST.js";
import { DELETE_CUSTOMER_ACCOUNT } from "./DELETE_CUSTOMER_ACCOUNT.js";
import { CUSTOMER_TECHNICIAN_LIST } from "./CUSTOMER_TECHNICIAN_LIST.js";

export { CUSTOMER_LIST, DELETE_CUSTOMER_ACCOUNT, CUSTOMER_TECHNICIAN_LIST };
